name: pr-deps-plotter
description: '✏️  Draw diagrams representing pull request dependencies.'
inputs:
  TOKEN:
    description: 'GitHub token to authenticate the action.'
    required: true
runs:
  using: composite
  steps:
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Run
      shell: bash
      run: |
        set -x
        PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
        [ PR_NUMBER = "main" ] && exit 0 || true
        sources=$(find src/ -name *.go -not \( -name *_test.go \))
        go run $sources "https://api.github.com/repos/$GITHUB_REPOSITORY/pull/$PR_NUMBER" ${{ inputs.TOKEN }} | dot -Tpng > /tmp/pr-deps-plotter.png
        PREVIOUS_COMMENT=$(curl -L \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments | jq '.[] | select(.body | strings | test("PRDepPlotter")) | .id' \
          || true
        )
        upload_path=$(curl --upload-file /tmp/pr-deps-plotter.png https://transfer.sh/pr-deps-plotter.png)

        [ -z $PREVIOUS_COMMENT ] &&
          curl -H 'Authorization: Token ${{ inputs.TOKEN }}' -X POST \
          -d '{"body": "<!-- PRDepPlotter -->\nDependency graph for this PR:\n[![PR Deps]('$(echo $upload_path)')]()\nImage hosted at: '$upload_path'"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
        || \
          curl -H 'Authorization: Token ${{ inputs.TOKEN }}' -X PATCH \
          -d '{"body": "<!-- PRDepPlotter -->\nDependency graph for this PR:\n[![PR Deps]('$(echo $upload_path)')]()\nImage hosted at: '$upload_path'"}' \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/comments/$PREVIOUS_COMMENT"


