name: Test

on:
  workflow_dispatch: # Run with Run Workflow button in GitHub Action Job, set debug_enabled=true for interactive ssh session.
    inputs:

jobs:
  pr-deps-plotter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        id: plot_deps
        uses: ./
        with:
          pr_url: 'https://github.com/wisespace-io/yubico-rs/pull/26'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Output result
        run: echo "Output ${{ steps.plot_deps.outputs.SVG }}"
