name: Test

on:
  pull_request

jobs:
  pr-deps-plotter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        id: plot_deps
        uses: ./
        with:
          pr_url: 'https://github.com/wisespace-io/yubico-rs/pull/26'
          token: ${{ secrets.GH_PAT }}
